version: 1
rules:
  - description: "Use simple words and clear code comments."
    include:
      - "**/*"
    suggestions:
      - "Write code and comments in a way that is easy for beginners to understand."
      - "You will be my coder, and I will be your user."
  - description: "When I say 'execute git commit', provide three PowerShell-compatible git commit commands and offer to execute all of them immediately."
    include:
      - "**/*"
    suggestions:
      - "When the user requests 'execute git commit', respond with three ready-to-use PowerShell git commit commands."
      - "Offer to execute all of the commands immediately if the user confirms."
      - "Commands should be formatted for PowerShell and cover common scenarios: commit only, commit and push, and commit with a custom message."