services:
  - type: web
    name: pb-webhook-server-staging
    env: node
    plan: starter
    region: oregon
    autoDeploy: true
    branch: feature/apify-posts-ingestion
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /basic-test
    # If this repo is connected in Render UI, repo/owner are inferred. You can also set explicitly:
    # repo: https://github.com/PartnerPiloting/pb-webhook-server
    # rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: ENVIRONMENT
        value: staging
      - key: APIFY_WEBHOOK_TOKEN
        sync: false # set in Render dashboard
      - key: APIFY_API_TOKEN
        sync: false # set in Render dashboard
      - key: AIRTABLE_API_KEY
        sync: false # set in Render dashboard
      - key: MASTER_CLIENTS_BASE_ID
        sync: false # set in Render dashboard
      - key: AIRTABLE_BASE_ID
        sync: false # optional; used for legacy paths
      - key: PB_WEBHOOK_SECRET
        sync: false # for admin/repair endpoints if needed
      - key: GPT_CHAT_URL
        value: "https://chat.openai.com/g/g-680f15b60d148191920730b28b5509ae-li-messaging-from-at?workspace=personal"
      # Gemini/OpenAI keys are optional for webhook ingestion; if you also run scoring on staging, add them too:
      # - key: OPENAI_API_KEY
      #   sync: false
      # - key: GCP_PROJECT_ID
      #   sync: false
      # - key: GCP_LOCATION
      #   sync: false
      # - key: GEMINI_MODEL_ID
      #   value: gemini-2.5-flash
      # - key: GEMINI_EDITING_MODEL_ID
      #   value: gemini-2.5-pro
      # - key: GOOGLE_APPLICATION_CREDENTIALS
      #   sync: false # if using a mounted file/secret
  - type: cron
    name: airtable-warm-pinger
    runtime: node
    plan: starter
    schedule: "* * * * *" # adjust cron frequency as desired (e.g., every 5 minutes)
    envVars:
      - key: AIRTABLE_API_KEY
        sync: false
      - key: MASTER_CLIENTS_BASE_ID
        sync: false
      - key: AIRTABLE_TABLE_NAME
        sync: false
    buildCommand: "echo 'No build'"
    startCommand: "node scripts/airtable-warm/index.js"

  - type: cron
    name: apify-harvest-level2
    runtime: node
    plan: starter
    schedule: "0 * * * *" # hourly on the hour (adjust as needed)
    envVars:
      - key: API_PUBLIC_BASE_URL
        sync: false
      - key: PB_WEBHOOK_SECRET
        sync: false
    buildCommand: "echo 'No build'"
    startCommand: "node scripts/apify-harvest-level2/index.js"

  - type: cron
    name: post-score-level2
    runtime: node
    plan: starter
    schedule: "15 * * * *" # 15 minutes past the hour, after harvest
    envVars:
      - key: API_PUBLIC_BASE_URL
        sync: false
      # Optional tuning variables
      # - key: LIMIT
      #   value: "50"
      # - key: MIN_SERVICE_LEVEL
      #   value: "2"
      # - key: DRY_RUN
      #   value: "false"
      # - key: VERBOSE_ERRORS
      #   value: "true"
      # - key: MAX_VERBOSE_ERRORS
      #   value: "25"
      # - key: MARK_SKIPS
      #   value: "true"
      # - key: TABLE
      #   value: "Leads"
    buildCommand: "echo 'No build'"
    startCommand: "node scripts/post-score-level2/index.js"

  - type: cron
    name: daily-client-alerts
    runtime: node
    plan: starter
    schedule: "0 9 * * *" # 9:00 AM daily (AEST/AEDT)
    envVars:
      - key: AIRTABLE_API_KEY
        sync: false
      - key: MASTER_CLIENTS_BASE_ID
        sync: false
      - key: MAILGUN_API_KEY
        sync: false
      - key: MAILGUN_DOMAIN
        sync: false
      - key: FROM_EMAIL
        sync: false
      - key: ALERT_EMAIL
        sync: false
    buildCommand: "echo 'No build'"
    startCommand: "node scripts/daily-client-alerts/index.js"
