services:
  - type: web
    name: linkedin-messaging-followup-next
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: PORT
        value: 3000 