/**
 * Pending-reply handler — "just reply with their LinkedIn" made real.
 *
 * The tell-the-coach email (pendingLeadNotifier) sets Reply-To to a unique
 * add-<token>@<inbound domain> address. The coach's reply rides the EXISTING Mailgun inbound route
 * (*@mail.australiansidehustles.com.au → /api/webhooks/inbound-email — the same pipe as the track@
 * BCC tracker); the route hands add-* recipients here BEFORE the BCC flow.
 *
 * TRUST GATES (inbound email is an untrusted channel — all three must pass before any write):
 *   1. Mailgun webhook signature — validated by the route (unchanged posture).
 *   2. The token must match a live pending entry (unguessable, stamped at notify time, dies when
 *      the pending resolves).
 *   3. The SENDER must resolve (via inboundEmailService.findClientByEmail — primary or alternate
 *      addresses) to the SAME tenant the token belongs to. A stranger who somehow learns a token
 *      still can't plant records.
 *
 * PARSE (deterministic, no AI): a LinkedIn /in/ URL is the actionable signal; a clear "no/don't
 * add" is a decline; anything else gets ONE gentle "couldn't spot a LinkedIn link" nudge — and
 * auto-generated mail (out-of-office etc.) is dropped silently so no loop can start. NEVER create
 * a record from noise.
 *
 * ACT (all proven pieces): createLead (dedup-aware) with email = the PENDING email — exactly what
 * makes resolvePendingLeadByEmail attach the waiting transcripts; a better email from the reply
 * becomes the primary afterwards (updateLeadEmails preserves the old one into Alt Emails); then a
 * short confirmation email back to the coach.
 */

const https = require('https');
const querystring = require('querystring');
const { createSafeLogger } = require('../utils/loggerHelper');

const log = createSafeLogger('SYSTEM', null, 'pending_reply');

const EMAIL_RE = /[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}/gi;
const LINKEDIN_RE = /(?:https?:\/\/)?(?:[a-z]{2,3}\.)?linkedin\.com\/in\/([A-Za-z0-9\-_%.]+)/i;
const DECLINE_RE = /\b(no thanks|don'?t add|do not add|not interested|please ignore|skip (her|him|them|this one)|leave (her|him|them) out)\b/i;

/** Plain Mailgun send (same shape as pendingLeadNotifier). */
function sendMailgun(emailData) {
  if (!process.env.MAILGUN_API_KEY || !process.env.MAILGUN_DOMAIN) {
    return Promise.reject(new Error('Mailgun not configured'));
  }
  return new Promise((resolve, reject) => {
    const data = querystring.stringify(emailData);
    const auth = Buffer.from(`api:${process.env.MAILGUN_API_KEY}`).toString('base64');
    const req = https.request({
      hostname: 'api.mailgun.net', port: 443,
      path: `/v3/${process.env.MAILGUN_DOMAIN}/messages`, method: 'POST',
      headers: { Authorization: `Basic ${auth}`, 'Content-Type': 'application/x-www-form-urlencoded', 'Content-Length': data.length },
    }, (res) => {
      let body = '';
      res.on('data', (c) => { body += c; });
      res.on('end', () => (res.statusCode >= 200 && res.statusCode < 300 ? resolve(body) : reject(new Error(`Mailgun ${res.statusCode}: ${String(body).slice(0, 200)}`))));
    });
    req.on('error', reject);
    req.write(data);
    req.end();
  });
}

/** Auto-generated mail (out-of-office, bounces) must never trigger a reply from us — loop guard. */
function isAutoGenerated(mailgunData) {
  let headers = [];
  try { headers = JSON.parse(mailgunData['message-headers'] || '[]'); } catch (_) { /* tolerate */ }
  for (const [name, value] of headers) {
    const n = String(name).toLowerCase();
    const v = String(value).toLowerCase();
    if (n === 'auto-submitted' && v !== 'no') return true;
    if (n === 'precedence' && /(auto_reply|bulk|junk)/.test(v)) return true;
    if (n === 'x-autoreply' || n === 'x-autorespond') return true;
  }
  return false;
}

/** Parse the human part of the reply into an intent. */
function parseReply(mailgunData, person, senderEmail) {
  const text = String(mailgunData['stripped-text'] || mailgunData['body-plain'] || '').slice(0, 4000);
  const li = text.match(LINKEDIN_RE);
  const linkedinUrl = li ? `https://www.linkedin.com/in/${li[1].replace(/[.,;)\]]+$/, '')}/` : '';
  const declined = !linkedinUrl && DECLINE_RE.test(text.slice(0, 400));
  // A different plausible email in the reply = "her real address is..." (the calendar one stays as
  // an alternate). Exclude the pending email, the sender's own, and our infrastructure domains.
  let betterEmail = '';
  const own = new Set([person.email, String(senderEmail || '').toLowerCase()]);
  for (const m of text.match(EMAIL_RE) || []) {
    const e = m.toLowerCase();
    if (own.has(e) || /mail\.australiansidehustles\.com\.au|mailgun/.test(e)) continue;
    betterEmail = e;
    break;
  }
  // Phone: first plausible run of 8+ digits (allowing spaces/dashes/parens/+).
  const ph = text.replace(EMAIL_RE, ' ').match(/(\+?\d[\d\s\-()]{6,}\d)/);
  const phone = ph && ph[1].replace(/\s+/g, ' ').trim().replace(/\D/g, '').length >= 8 ? ph[1].replace(/\s+/g, ' ').trim() : '';
  return { linkedinUrl, declined, betterEmail, phone };
}

/**
 * Handle one inbound Mailgun message IF it is a reply to a pending-lead notification.
 * @returns {Promise<{handled:boolean, outcome?:string}>} handled=false → not ours, let the BCC flow run.
 */
async function handlePendingReply(mailgunData) {
  const recipient = String(mailgunData.recipient || '').toLowerCase().trim();
  const tokenMatch = recipient.match(/^add-([a-z0-9_-]{8,32})@/i);
  if (!tokenMatch) return { handled: false };
  const token = tokenMatch[1];

  if (isAutoGenerated(mailgunData)) {
    log.info(`pending reply: auto-generated mail to ${recipient} — dropped`);
    return { handled: true, outcome: 'dropped-auto-reply' };
  }

  // Lazy requires (same convention as the other Wingguy services — module load must not need env).
  const db = require('./recallWebhookDb');
  const inboundEmailService = require('./inboundEmailService');
  const clientService = require('./clientService');
  const wingguyLeads = require('./wingguyLeads');

  // GATE 2 — the token must belong to a LIVE pending entry.
  const rows = await db.findPendingLeadMeetings({ limit: 200 });
  let hit = null;
  for (const m of rows) {
    const entry = m.pending.find((x) => x.replyToken === token);
    if (entry) { hit = { coachClientId: m.coach_client_id, person: entry, meetings: (hit ? hit.meetings : []).concat(m) }; }
  }
  if (!hit) {
    log.info(`pending reply: token ${token.slice(0, 4)}… matches no live pending entry (resolved already, or stale) — dropped`);
    return { handled: true, outcome: 'dropped-unknown-token' };
  }

  // GATE 3 — the sender must be the tenant the token belongs to.
  const senderEmail = String(mailgunData.sender || mailgunData.from || '').replace(/^.*</, '').replace(/>.*$/, '').toLowerCase().trim();
  const senderClient = await inboundEmailService.findClientByEmail(senderEmail);
  if (!senderClient || senderClient.clientId !== hit.coachClientId) {
    log.warn(`pending reply: sender ${senderEmail} does not resolve to tenant ${hit.coachClientId} — dropped`);
    return { handled: true, outcome: 'dropped-sender-mismatch' };
  }

  const coach = await clientService.getClientById(hit.coachClientId);
  const coachTo = coach && String(coach.clientEmailAddress || '').trim();
  const from = `Wingguy <wingguy@${process.env.MAILGUN_DOMAIN}>`;
  const person = hit.person;
  const shortWho = person.name || person.email;
  const { linkedinUrl, declined, betterEmail, phone } = parseReply(mailgunData, person, senderEmail);

  // --- DECLINED -------------------------------------------------------------
  if (declined) {
    await db.markPendingLeadDeclined({ coachClientId: hit.coachClientId, email: person.email });
    if (coachTo) {
      await sendMailgun({ from, to: coachTo, subject: `Re: Want me to add ${shortWho} to your contacts?`, text: `No worries - I won't ask about ${shortWho} again.\n\n- Wingguy` }).catch((e) => log.warn(`decline ack failed: ${e.message}`));
    }
    log.info(`pending reply: ${hit.coachClientId} declined ${person.email}`);
    return { handled: true, outcome: 'declined' };
  }

  // --- NO LINK, NOT A DECLINE — one gentle nudge ---------------------------
  if (!linkedinUrl) {
    if (coachTo) {
      await sendMailgun({
        from, to: coachTo, subject: `Re: Want me to add ${shortWho} to your contacts?`,
        text: `I couldn't spot a LinkedIn link in your reply. Paste ${shortWho}'s LinkedIn profile URL (linkedin.com/in/...) and reply again - I'll take it from there. Or just say "don't add" and I'll drop it.\n\n- Wingguy`,
        'h:Reply-To': recipient, // keep the same add-token thread alive for the retry
      }).catch((e) => log.warn(`nudge failed: ${e.message}`));
    }
    log.info(`pending reply: no LinkedIn URL in reply for ${person.email} — nudged`);
    return { handled: true, outcome: 'nudged-no-link' };
  }

  // --- CREATE + ATTACH ------------------------------------------------------
  const nameParts = String(person.name || '').trim().split(/\s+/);
  const firstName = nameParts.slice(0, -1).join(' ') || nameParts[0] || '';
  const lastName = nameParts.length > 1 ? nameParts[nameParts.length - 1] : '';
  const r = await wingguyLeads.createLead(coach.airtableBaseId, {
    firstName, lastName,
    linkedinUrl,
    email: person.email, // the pending email IS the attach key — resolve below depends on it
    phone,
    notes: `Added by replying to Wingguy's meeting email (met ${person.email}).`,
  });
  if (!r || !r.ok) {
    log.warn(`pending reply: createLead failed for ${person.email}: ${(r && r.error) || 'unknown'}`);
    if (coachTo) {
      await sendMailgun({ from, to: coachTo, subject: `Re: Want me to add ${shortWho} to your contacts?`, text: `I hit a snag adding ${shortWho} (${(r && r.error) || 'unknown error'}). Tell me in a Wingguy chat and I'll sort it there.\n\n- Wingguy`, 'h:Reply-To': recipient }).catch(() => {});
    }
    return { handled: true, outcome: 'create-failed' };
  }

  const resolved = await db.resolvePendingLeadByEmail({ email: person.email, airtableLeadId: r.leadRecordId, coachClientId: hit.coachClientId, source: 'reply-to-add' });
  const attached = (resolved.linked || []).length;

  // A better email in the reply becomes the primary; the calendar one is preserved as an alternate.
  let emailNote = '';
  if (betterEmail) {
    try {
      const u = await wingguyLeads.updateLeadEmails(coach.airtableBaseId, r.leadRecordId, { setPrimary: betterEmail });
      if (u.ok) emailNote = ` Primary email set to ${betterEmail} (${person.email} kept as an alternate).`;
    } catch (e) { log.warn(`better-email update failed: ${e.message}`); }
  }

  if (coachTo) {
    const already = r.exists ? ` (they were already in your database - no duplicate made)` : '';
    await sendMailgun({
      from, to: coachTo, subject: `Re: Want me to add ${shortWho} to your contacts?`,
      text: `Done - ${shortWho} is in your Wingguy database${already}${attached ? `, with ${attached} meeting transcript(s) attached` : ''}.${phone ? ` Phone filed.` : ''}${emailNote}\n\nAsk me about your meetings with them any time.\n\n- Wingguy`,
    }).catch((e) => log.warn(`confirmation failed: ${e.message}`));
  }
  log.info(`pending reply: ${hit.coachClientId} added ${person.email} -> lead ${r.leadRecordId} (${attached} meeting(s) attached${r.exists ? ', dedup hit' : ''})`);
  return { handled: true, outcome: r.exists ? 'linked-existing' : 'created', leadRecordId: r.leadRecordId, attached };
}

module.exports = { handlePendingReply, parseReply, isAutoGenerated };
