# GitHub Action to check syntax before deployment
name: Syntax Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Check JavaScript syntax
      run: |
        # Check all JS files for syntax errors
        find . -name "*.js" -not -path "./node_modules/*" | xargs -I {} node -c {}
        
    - name: Run ESLint (if configured)
      run: |
        if [ -f .eslintrc.js ] || [ -f .eslintrc.json ]; then
          npx eslint . --ext .js
        fi
